# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat: puppetlabs/concat
    cron_core: puppetlabs/cron_core
    postgresql:
      repo: puppetlabs/postgresql
      ref: 8.2.1
    sshkeys_core: puppetlabs/sshkeys_core
    stdlib: puppetlabs/stdlib
    inifile:
      repo: puppetlabs/inifile
      ref: 5.4.0
